services:
  - type: web
    name: classmate-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: classmate-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0